<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="VIVEK" name="ValidateTitle" tests="1" failures="1" timestamp="8 Jan 2021 00:43:22 GMT" time="41.06" errors="0">
  <testcase name="failedTC" time="2.811" classname="VIK.Framework.ValidateTitle">
    <failure type="java.lang.AssertionError" message="expected [my account] but found [AUTHENTICATION]">
      <![CDATA[java.lang.AssertionError: expected [my account] but found [AUTHENTICATION]
	at VIK.Framework.ValidateTitle.failedTC(ValidateTitle.java:39)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- failedTC -->
</testsuite> <!-- ValidateTitle -->
